Repository NVIDIA/spark-rapids-jni, pull requests merged in 2022-07, with the labels that each got.

#362 Add new native parquet footer API and deprecate the old one
  src/main/java/com/nvidia/spark/rapids/jni/ParquetFooter.java
Labels: enhancement

#367 Remove superfluous $CMAKE_GENERATOR
  build/build-in-docker
  build/run-in-docker
Labels: build

#365 Add in better native parquet footer implementation and remove the old one
  src/main/cpp/src/NativeParquetJni.cpp
  src/main/java/com/nvidia/spark/rapids/jni/ParquetFooter.java
Labels: bug

#381 Document local cross-repo testing for spark-rapids, spark-rapids-jni, and cudf [skip ci]
  CONTRIBUTING.md
Labels: documentation

#389 Enable cpp tests
  ci/nightly-build.sh
  ci/premerge-build.sh
  pom.xml
Labels: enhancement

#405 Enable auto-merge from branch-22.08 to branch-22.10 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build
