Repository NVIDIA/spark-rapids-jni, pull requests merged in 2022-10, with the labels that each got.

#562 Adding single kernel for string to decimal casting
  src/main/cpp/src/CastStringJni.cpp
  src/main/cpp/src/cast_string.cu
  src/main/cpp/src/cast_string.hpp
  src/main/cpp/tests/cast_string.cpp
  src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java
Labels: enhancement

#595 Make docker run -i -t optional via EXTRA ARGS
  build/run-in-docker
Labels: build

#611 Fixing incorrect invalidation of positive cudf scale decimal values
  src/main/cpp/src/cast_string.cu
  src/main/cpp/tests/cast_string.cpp
Labels: bug

#627 Adding spark-rapids-jni PRs to global Github project [skip ci]
  .github/workflows/add-to-project.yml
Labels: build

#633 Fixing empty columns when casting to integer or decimal crashing
  src/main/cpp/src/cast_string.cu
  src/main/cpp/tests/cast_string.cpp
Labels: bug

#643 Verify automerge fix of Token permission
  .github/workflows/auto-merge.yml
Labels: build

#644 Revert not working automerge fix [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#647 Workaround to not use GITHUB_TOKEN checkout code in automerge [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#657 Fix deprecated Github actions API [skip ci]
  .github/workflows/add-to-project.yml
  .github/workflows/auto-merge.yml
  .github/workflows/blossom-ci.yml
Labels: bug, build

#658 Fix setup-java step of blossom-ci [skip ci]
  .github/workflows/blossom-ci.yml
Labels: bug, build

#660 Update signoff checkout action ver to V3 [skip ci]
  .github/workflows/signoff-check.yml
Labels: bug, build

#631 Adding cast string to float kernel
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/CastStringJni.cpp
  src/main/cpp/src/cast_string.hpp
  src/main/cpp/src/cast_string_to_float.cu
  src/main/cpp/tests/cast_string.cpp
  src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java
Labels: enhancement

#676 Adding float casting benchmark
  src/main/cpp/benchmarks/CMakeLists.txt
  src/main/cpp/benchmarks/cast_string_to_float.cpp
Labels: enhancement

#681 Explicitly pass stream to cudf detail APIs
  src/main/cpp/benchmarks/cast_string_to_float.cpp
  src/main/cpp/benchmarks/common/generate_input.cu
Labels: build
