Repository NVIDIA/spark-rapids-jni, pull requests merged in 2022-09, with the labels that each got.

#504 adding clang-format for cpp files
  .pre-commit-config.yaml
Labels: enhancement

#503 Adding test framework for casting and integer casting kernel and tests
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/CastStringJni.cpp
  src/main/cpp/src/cast_string.cu
  src/main/cpp/src/cast_string.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/cast_string.cpp
  src/main/java/com/nvidia/spark/rapids/jni/CastException.java
  src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java
  src/test/java/com/nvidia/spark/rapids/jni/CastStringsTest.java
Labels: enhancement

#534 Mvn batch-mode for CI scripts
  ci/deploy.sh
  ci/nightly-build.sh
  ci/premerge-build.sh
  ci/submodule-sync.sh
Labels: build

#559 Enable automerge from 22.10 to 22.12 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#560 Init JNI version 22.12.0-SNAPSHOT
  .gitmodules
  CONTRIBUTING.md
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build

#580 Update location of clang-format file in cudf
  .pre-commit-config.yaml
Labels: bug
