Repository NVIDIA/spark-rapids-jni, pull requests merged in 2023-11, with the labels that each got.

#1536 Fix underflow during subtraction in `map_utils.cu#from_json`
  src/main/cpp/src/map_utils.cu
Labels: bug

#1537 Implement timestamp rebase from Julian to Gregorian calendars
  src/main/cpp/src/DateTimeRebaseJni.cpp
  src/main/cpp/src/datetime_rebase.cu
  src/main/cpp/src/datetime_rebase.hpp
  src/main/cpp/tests/datetime_rebase.cpp
  src/main/java/com/nvidia/spark/rapids/jni/DateTimeRebase.java
  src/test/java/com/nvidia/spark/rapids/jni/DateTimeRebaseTest.java
Labels: feature request

#1555 Enable automerge from 23.12 to 24.02 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1577 Fix row conversion test
  src/main/cpp/src/row_conversion.cu
Labels: bug

#1583 Fix default values for stream parameter
  src/main/cpp/src/decimal_utils.hpp
  src/main/cpp/src/parse_uri.hpp
  src/main/cpp/src/row_conversion.hpp
Labels: bug

#1587 Remove `.clang-format` style and update docs [skip ci]
  CONTRIBUTING.md
  src/main/cpp/.clang-format
Labels: documentation, enhancement

#1591 Fixing potential overflow in array read in string to float cast
  src/main/cpp/src/cast_string_to_float.cu
Labels: bug

#1597 Add github action for C++ `clang-format` style check
  .github/workflows/clang-format.yml
  src/main/cpp/src/DateTimeRebaseJni.cpp
  src/main/cpp/src/HistogramJni.cpp
  src/main/cpp/src/cast_string_to_float.cu
  src/main/cpp/src/datetime_rebase.cu
  src/main/cpp/src/datetime_rebase.hpp
  src/main/cpp/src/histogram.cu
  src/main/cpp/src/histogram.hpp
  src/main/cpp/src/map_utils.cu
  src/main/cpp/src/row_conversion.cu
  src/main/cpp/tests/datetime_rebase.cpp
Labels: build, test

#1543 Update state retry state machine for CPU alloc support
  src/main/cpp/src/SparkResourceAdaptorJni.cpp
  src/main/java/com/nvidia/spark/rapids/jni/CpuRetryOOM.java
  src/main/java/com/nvidia/spark/rapids/jni/CpuSplitAndRetryOOM.java
  src/main/java/com/nvidia/spark/rapids/jni/GpuRetryOOM.java
  src/main/java/com/nvidia/spark/rapids/jni/GpuSplitAndRetryOOM.java
  src/main/java/com/nvidia/spark/rapids/jni/OffHeapOOM.java
  src/main/java/com/nvidia/spark/rapids/jni/RmmSpark.java
  src/main/java/com/nvidia/spark/rapids/jni/RmmSparkThreadState.java
  src/main/java/com/nvidia/spark/rapids/jni/SparkResourceAdaptor.java
  src/main/java/com/nvidia/spark/rapids/jni/ThreadStateRegistry.java
  src/test/java/com/nvidia/spark/rapids/jni/LimitingOffHeapAllocForTests.java
  src/test/java/com/nvidia/spark/rapids/jni/RmmSparkMonteCarlo.java
  src/test/java/com/nvidia/spark/rapids/jni/RmmSparkTest.java
Labels: reliability
