Repository NVIDIA/spark-rapids-jni, pull requests merged in 2023-05, with the labels that each got.

#1115 Pin urllib3<2.0 to resolve requests lib issue for CI scripts [skip ci]
  .github/workflows/action-helper/Dockerfile
  ci/Dockerfile
Labels: bug, build

#1137 Pre-merge docker build stage to support containerd runtime [skip ci]
  ci/Jenkinsfile.premerge
Labels: build

#1141 Remove repeated exception class name
  src/main/cpp/src/RowConversionJni.cpp
  src/main/cpp/src/SparkResourceAdaptorJni.cpp
Labels: enhancement

#1143 Fix build with CUDA 12
  src/main/cpp/CMakeLists.txt
Labels: bug

#1146 Avoid a race in retry where we might do a split when we don't need to
  src/main/cpp/src/SparkResourceAdaptorJni.cpp
  src/test/java/com/nvidia/spark/rapids/jni/RmmSparkMonteCarlo.java
  src/test/java/com/nvidia/spark/rapids/jni/RmmSparkTest.java
Labels: reliability

#1148 Ensure columns have valid null counts.
  src/main/cpp/src/row_conversion.cu
Labels: bug

#1158 Enable auto-merge branch-23.06 to branch-23.08 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1172 Fixing float to string not setting null count
  src/main/cpp/src/cast_string_to_float.cu
Labels: bug

#1175 Implement Remainder for Decimal128 that handles when operands overflow
  src/main/cpp/src/DecimalUtilsJni.cpp
  src/main/cpp/src/decimal_utils.cu
  src/main/cpp/src/decimal_utils.hpp
  src/main/java/com/nvidia/spark/rapids/jni/DecimalUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/DecimalUtilsTest.java
Labels: enhancement

#1168 Adding non-ansi decimal to string conversion
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/CastStringJni.cpp
  src/main/cpp/src/cast_decimal_to_string.cu
  src/main/cpp/src/cast_string.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/cast_decimal_to_string.cpp
  src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java
Labels: enhancement, feature request
