Repository NVIDIA/spark-rapids-jni, pull requests merged in 2023-10, with the labels that each got.

#1482 enable sanitizer in Arm64 build [skip ci]
  ci/nightly-build.sh
Labels: bug, build

#1485 [BUG] fix docker modified check in premerge [skip ci]
  ci/Jenkinsfile.premerge
Labels: bug, build

#1416 Implement `percentile` computation from `histogram` data
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/HistogramJni.cpp
  src/main/cpp/src/histogram.cu
  src/main/cpp/src/histogram.hpp
  src/main/java/com/nvidia/spark/rapids/jni/Histogram.java
Labels: feature request

#1504 Update blossom-ci ACL [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#1502 Adding kernel to add parse_uri support for protocol extraction
  src/main/cpp/CMakeLists.txt
  src/main/cpp/benchmarks/CMakeLists.txt
  src/main/cpp/benchmarks/parse_uri.cpp
  src/main/cpp/src/ParseURIJni.cpp
  src/main/cpp/src/parse_uri.cu
  src/main/cpp/src/parse_uri.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/parse_uri.cpp
  src/main/java/com/nvidia/spark/rapids/jni/ParseURI.java
  src/test/java/com/nvidia/spark/rapids/jni/ParseURITest.java
Labels: enhancement, feature request

#1506 Patch parcentile evaluation to produce similar output as Spark CPU
  src/main/cpp/src/histogram.cu
Labels: reliability

#1521 Append new authorized user to blossom-ci whitelist [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build
