Repository NVIDIA/spark-rapids-jni, pull requests merged in 2023-03, with the labels that each got.

#997 Add fuzz-test CI script
  ci/Jenkinsfile.premerge
  ci/fuzz-test.sh
Labels: test

#1016 Add -DBUILD_TESTS=ON to submodule sync [skip ci]
  ci/submodule-sync.sh
Labels: bug, build

#1028 Enable automerge from 2304 to 2306 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1037 Add license file int jar's META-INF/ dir
  pom.xml
Labels: bug, build
