Repository NVIDIA/spark-rapids-jni, pull requests merged in 2023-08, with the labels that each got.

#1303 Rework BloomFilter interface
  src/main/cpp/CMakeLists.txt
  src/main/cpp/benchmarks/CMakeLists.txt
  src/main/cpp/benchmarks/bloom_filter.cu
  src/main/cpp/benchmarks/common/generate_input.cu
  src/main/cpp/src/BloomFilterJni.cpp
  src/main/cpp/src/bloom_filter.cu
  src/main/cpp/src/bloom_filter.hpp
  src/main/cpp/src/murmur_hash.cu
  src/main/cpp/src/murmur_hash.cuh
  src/main/cpp/src/utilities.cu
  src/main/cpp/src/utilities.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/bloom_filter.cu
  src/main/cpp/tests/utilities.cpp
  src/main/java/ai/rapids/cudf/CudfAccessor.java
  src/main/java/com/nvidia/spark/rapids/jni/BloomFilter.java
  src/test/java/com/nvidia/spark/rapids/jni/BloomFilterTest.java
Labels: feature request

#1347 Update sanitizer settings for ci [skip ci]
  ci/premerge-build.sh
  ci/submodule-sync.sh
Labels: build

#1314 Add JNI backend for Spark SQL function `conv` for (hexa)decimals
  src/main/cpp/src/CastStringJni.cpp
  src/main/cpp/src/row_conversion.cu
  src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java
  src/test/java/com/nvidia/spark/rapids/jni/CastStringsTest.java
Labels: feature request

#1364 Avoid using invlalid null_mask for zero null_count
  src/main/cpp/src/CastStringJni.cpp
  src/test/java/com/nvidia/spark/rapids/jni/CastStringsTest.java
Labels: bug
