Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-11, with the labels that each got.

#2557 Improve `concat_json`
  src/main/cpp/src/JSONUtilsJni.cpp
  src/main/cpp/src/json_utils.cu
  src/main/cpp/src/json_utils.hpp
Labels: feature request

#2583 Prepare the arg to disable kvikIO remote IO
  pom.xml
Labels: build

#2584 [POST cleanup] Remove the kvikIO workaround KvikIO_REMOTE_SUPPORT=OFF
  pom.xml
Labels: bug, build

#2562 Improve `from_json_to_raw_map`
  src/main/cpp/src/JSONUtilsJni.cpp
  src/main/cpp/src/from_json_to_raw_map.cu
  src/main/cpp/src/from_json_to_raw_map_debug.cuh
  src/main/cpp/src/json_utils.hpp
  src/main/java/com/nvidia/spark/rapids/jni/JSONUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/FromJsonToRawMapTest.java
Labels: bug, enhancement

#2588 Workaround to apply cudf's thirdparty patches for cudf-pins build [skip ci]
  ci/submodule-sync.sh
Labels: bug, build

#2597 Update cmake to 3.28.6
  ci/Dockerfile
Labels: build

#2594 Update method for locating cufile and remove unused libcudf cmake options
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build

#2607 Fix non-empty nulls handling in `string_to_decimal` and add more tests for non-empty nulls
  src/main/cpp/src/cast_string.cu
  src/main/cpp/tests/cast_string.cpp
Labels: bug

#2605 Copyright header check [skip ci]
  .github/workflows/license-header-check.yml
Labels: build

#2616 Fix bug license header check [skip ci]
  .github/workflows/license-header-check.yml
Labels: bug

#2510 Implement `from_json_to_structs`
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/JSONUtilsJni.cpp
  src/main/cpp/src/from_json_to_structs.cu
  src/main/cpp/src/json_utils.cu
  src/main/cpp/src/json_utils.hpp
  src/main/java/com/nvidia/spark/rapids/jni/JSONUtils.java
Labels: enhancement, performance, feature request
