Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-05, with the labels that each got.

#2015 Adjust the launch bounds to get_json_object to avoid spilling
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/json_parser.cuh
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: performance

#2030 Fix null handling in `percentile` evaluation when the input histogram is empty
  src/main/cpp/src/histogram.cu
  src/test/java/com/nvidia/spark/rapids/jni/HistogramTest.java
Labels: bug

#2010 Drop Centos7 support
  build/build-in-docker
  build/run-in-docker
  ci/Dockerfile
  ci/Dockerfile.multi
  ci/Jenkinsfile.premerge
  ci/submodule-sync.sh
  pom.xml
Labels: build

#2042 Add Python requests module to Dockerfile
  ci/Dockerfile
Labels: build

#2052 Add Paul to build permissions list
  .github/workflows/blossom-ci.yml
Labels: build

#2068 Auto merge PRs to branch-24.08 from branch-24.06 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#2089 Typo in contributor documentation [skip ci]
  CONTRIBUTING.md
Labels: documentation

#2098 Fix nvtx3 linking issue in benchmark
  src/main/cpp/benchmarks/CMakeLists.txt
Labels: bug, build
