Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-12, with the labels that each got.

#2646 Fix content error in documentation
  CONTRIBUTING.md
  src/main/cpp/faultinj/README.md
Labels: documentation

#2633 Remove handling code for mismatched nested schemas
  src/main/cpp/src/from_json_to_structs.cu
Labels: tech debt

#2660 Implement date/time truncation functions
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/DateTimeUtilsJni.cpp
  src/main/cpp/src/datetime_rebase.cu
  src/main/cpp/src/datetime_rebase.hpp
  src/main/cpp/src/datetime_truncate.cu
  src/main/cpp/src/datetime_utils.hpp
  src/main/cpp/tests/datetime_rebase.cpp
  src/main/java/com/nvidia/spark/rapids/jni/DateTimeRebase.java
  src/main/java/com/nvidia/spark/rapids/jni/DateTimeUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/DateTimeRebaseTest.java
  src/test/java/com/nvidia/spark/rapids/jni/DateTimeUtilsTest.java
Labels: feature request

#2673 Update copyright of modified files in branch-24.12 [skip ci]
  src/main/cpp/src/from_json_to_raw_map_debug.cuh
  src/test/java/com/nvidia/spark/rapids/jni/RmmSparkTest.java
Labels: bug, documentation

#2677 Refactor native build to a shell script
  build/buildcpp.sh
  pom.xml
Labels: build

#2679 Fetch `spdlog` without depending on `cudf`
  src/main/cpp/CMakeLists.txt
  src/main/cpp/cmake/get_spdlog.cmake
Labels: bug, tech debt

#2684 Update submodule sync to run buildcpp target [skip ci]
  ci/submodule-sync.sh
Labels: bug, build

#2682 Remove `CudfAccessor.java` and adopt new public methods from `Scalar.java`
  src/main/java/ai/rapids/cudf/CudfAccessor.java
  src/main/java/com/nvidia/spark/rapids/jni/BloomFilter.java
  src/main/java/com/nvidia/spark/rapids/jni/GpuSubstringIndexUtils.java
  src/main/java/com/nvidia/spark/rapids/jni/RegexRewriteUtils.java
Labels: tech debt
