Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-06, with the labels that each got.

#2108 Add new user to blossom-ci allow list [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2109 Add default value for REF of premerge jenkinsfile to avoid bad overwrittern [skip ci]
  ci/Jenkinsfile.premerge
Labels: build

#2063 Fix cast_string_to_float with trailing whitespaces for inf and nan string
  src/main/cpp/src/cast_string_to_float.cu
  src/test/java/com/nvidia/spark/rapids/jni/CastStringsTest.java
Labels: bug

#2137 Update blossom-ci ACL to secure format [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2136 Pin rapids-cmake across all cmake invocations
  pom.xml
Labels: bug, build

#2115 Inline build-libcudf and simplify overall build
  CONTRIBUTING.md
  build-libcudf.xml
  build/run-in-docker
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build

#2129 Optimize `get_json_object` by calling the main kernel only once
  src/main/cpp/src/get_json_object.cu
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: performance

#2153 Make run-in-docker usable in other repos
  CONTRIBUTING.md
  build/run-in-docker
Labels: build, test

#2165 Restore static CUDA runtime linking
  src/main/cpp/CMakeLists.txt
Labels: build

#2160 upgrade blossom ci actions version [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2178 Flipped MACRO ordering to properly match style
  src/main/cpp/src/cast_string.cu
Labels: tech debt

#2173 Improve cuda dependencies check during build
  ci/check-cuda-dependencies.sh
  ci/nightly-build.sh
  ci/premerge-build.sh
  ci/submodule-sync.sh
Labels: build
