Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-07, with the labels that each got.

#2196 Fix compile issue with `bloom_filter` benchmark
  src/main/cpp/benchmarks/bloom_filter.cu
Labels: bug, build

#2197 Build benchmarks during CI/CD
  ci/nightly-build.sh
  ci/premerge-build.sh
Labels: build

#2220 Fix `get_json_object` producing wrong output with wildcard paths
  src/main/cpp/src/get_json_object.cu
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: bug

#2228 Fix completion condition for `get_json_object` with wildcard paths but empty input array
  src/main/cpp/src/get_json_object.cu
Labels: bug

#2232 Cleanup `get_json_object`
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/get_json_object.hpp
  src/main/cpp/src/json_parser.cuh
Labels: enhancement

#2233 Implement `get_json_object_multiple_paths`
  src/main/cpp/src/JSONUtilsJni.cpp
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/get_json_object.hpp
  src/main/java/com/nvidia/spark/rapids/jni/JSONUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: performance

#2238 Mount workree common dir in build docker
  build/run-in-docker
Labels: bug, build

#2241 Add `nvtx` macro for `get_json_object` and `get_json_object_multiple_paths`
  src/main/cpp/src/get_json_object.cu
Labels: enhancement

#2246 Replace path-format=absolute with realpath
  build/run-in-docker
Labels: bug, build

#2253 Auto merge PRs to branch-24.10 from branch-24.08 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#2258 Implement hybrid thread/warp parallel kernel for `get_json_object`
  src/main/cpp/src/get_json_object.cu
Labels: performance

#2078 Implement kernel for casting float to decimal
  src/main/cpp/src/DecimalUtilsJni.cpp
  src/main/cpp/src/decimal_utils.cu
  src/main/cpp/src/decimal_utils.hpp
  src/main/java/com/nvidia/spark/rapids/jni/DecimalUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/DecimalUtilsTest.java
Labels: bug, enhancement

#2266 Detect and throw exception in `get_json_object` if the input has nesting depth exceed the maximum allowed value
  src/main/cpp/src/JSONUtilsJni.cpp
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/get_json_object.hpp
  src/main/cpp/src/json_parser.cuh
  src/main/java/com/nvidia/spark/rapids/jni/JSONUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: enhancement
