Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-03, with the labels that each got.

#1838 Move row conversion code from cudf
  src/main/cpp/CMakeLists.txt
  src/main/cpp/benchmarks/row_conversion.cpp
  src/main/cpp/src/RowConversionJni.cpp
  src/main/cpp/src/row_conversion.cu
  src/main/cpp/src/row_conversion.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/row_conversion.cpp
Labels: enhancement, tech debt

#1824 Move K8s cloud name into common lib for Jenkins CI
  ci/Jenkinsfile.premerge
Labels: build

#1853 Update to support checkout to the cudf release tag [skip ci]
  ci/submodule-sync.sh
Labels: build

#1858 Improve build-info script
  build/build-info
Labels: bug, build

#1874 Add guardword to hide cloud server info in pipeline
  ci/Jenkinsfile.premerge
Labels: build

#1895 Revert "Support cudf pin with rapids-cmake (#1877)"
  build-libcudf.xml
  ci/submodule-sync.sh
  pom.xml
  thirdparty/cudf-pins/add_dependency_pins.cmake
  thirdparty/cudf-pins/rapids-cmake.sha
  thirdparty/cudf-pins/setup.cmake
  thirdparty/cudf-pins/versions.json
Labels: build

#1887 Auto merge PRs to branch-24.06 from branch-24.04 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1888 Pin to 3.1.0 maven-gpg-plugin in deploy script [skip ci]
  ci/deploy.sh
Labels: build

#1908 Upate Git user for pre-merge CI
  .github/workflows/blossom-ci.yml
Labels: build
