Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-04, with the labels that each got.

#1901 Pin cudf dependencies during build
  build-libcudf.xml
  ci/submodule-sync.sh
  pom.xml
  thirdparty/cudf-pins/add_dependency_pins.cmake
  thirdparty/cudf-pins/rapids-cmake.sha
  thirdparty/cudf-pins/setup.cmake
  thirdparty/cudf-pins/versions.json
Labels: build

#1898 Update actions version [skip ci]
  .github/workflows/add-to-project.yml
  .github/workflows/auto-merge.yml
  .github/workflows/blossom-ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/signoff-check.yml
Labels: build

#1929 Remove tests of deleted cudf::hash HASH_MURMUR3
  pom.xml
  src/main/cpp/tests/hash.cpp
  thirdparty/cudf-pins/versions.json
Labels: bug

#1946 Fix auto merge conflict 1935
  .github/workflows/blossom-ci.yml
  ci/Jenkinsfile.premerge
  thirdparty/cudf-pins/versions.json
Labels: build

#1928 Avoid auto-merging thirdparty/cudf-pins
  .github/workflows/auto-merge.yml
Labels: build

#1930 getJsonObject: improve performance for new version of getJsonObject
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/get_json_object.hpp
  src/main/cpp/src/json_parser.cuh
  src/main/java/com/nvidia/spark/rapids/jni/JSONUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: enhancement, performance

#1954 Update comments and fix typo [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1940 Restore pinned cudf dependency mode
  pom.xml
Labels: build

#1952 Implement benchmark for `get_json_object`
  src/main/cpp/benchmarks/CMakeLists.txt
  src/main/cpp/benchmarks/common/generate_input.cu
  src/main/cpp/benchmarks/get_json_object.cu
  src/main/cpp/benchmarks/row_conversion.cpp
Labels: feature request

#1981 Remove inactive users
  .github/workflows/blossom-ci.yml
Labels: build

#1983 Explicitly pull in GTest dependency when building C++ tests
  src/main/cpp/CMakeLists.txt
Labels: build

#1978 Trim C0 control chars in string to number type conversion
  src/main/cpp/src/cast_string.cu
  src/main/cpp/src/cast_string_to_float.cu
  src/test/java/com/nvidia/spark/rapids/jni/CastStringsTest.java
Labels: bug

#1997 URI Path Parsing
  src/main/cpp/src/ParseURIJni.cpp
  src/main/cpp/src/parse_uri.cu
  src/main/cpp/src/parse_uri.hpp
  src/main/cpp/tests/parse_uri.cpp
  src/main/java/com/nvidia/spark/rapids/jni/ParseURI.java
  src/test/java/com/nvidia/spark/rapids/jni/ParseURITest.java
Labels: enhancement

#1987 Remove Path key/subscript to save GPU memory usage to improve perf
  src/main/cpp/src/get_json_object.cu
  src/test/java/com/nvidia/spark/rapids/jni/GetJsonObjectTest.java
Labels: performance
