Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-01, with the labels that each got.

#1673 Update copyright date in NOTICE file [skip ci]
  NOTICE
Labels: documentation

#1672 Download boost package for CI jobs
  ci/Dockerfile
  ci/Dockerfile.multi
Labels: bug, build

#1690 Add explicit mention of git submodule use at top of CONTRIBUTING.md [skip ci]
  CONTRIBUTING.md
Labels: documentation

#1722 Enable auto-merge from branch-24.02 to branch-24.04 [skip ci]
  .github/workflows/auto-merge.yml
Labels: build

#1704 Adding literal support for parse_uri for query
  src/main/cpp/src/ParseURIJni.cpp
  src/main/cpp/src/parse_uri.cu
  src/main/cpp/src/parse_uri.hpp
  src/main/cpp/tests/parse_uri.cpp
  src/main/java/com/nvidia/spark/rapids/jni/ParseURI.java
  src/test/java/com/nvidia/spark/rapids/jni/ParseURITest.java
Labels: enhancement, feature request

#1719 Add support for `parse_uri` to limit query with a column
  src/main/cpp/src/ParseURIJni.cpp
  src/main/cpp/src/parse_uri.cu
  src/main/cpp/src/parse_uri.hpp
  src/main/cpp/tests/parse_uri.cpp
  src/main/java/com/nvidia/spark/rapids/jni/ParseURI.java
  src/test/java/com/nvidia/spark/rapids/jni/ParseURITest.java
Labels: enhancement, feature request

#1746 Fix a out of bound bug in parse_url query
  src/main/cpp/src/parse_uri.cu
  src/test/java/com/nvidia/spark/rapids/jni/ParseURITest.java
Labels: bug
