Repository NVIDIA/spark-rapids-jni, pull requests merged in 2024-10, with the labels that each got.

#2457 Implement `concat_json` to join JSON strings given by strings column
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/JSONUtilsJni.cpp
  src/main/cpp/src/json_utils.cu
  src/main/cpp/src/json_utils.hpp
  src/main/java/com/nvidia/spark/rapids/jni/JSONUtils.java
Labels: feature request

#2483 Revert nvcomp
  build/apply-patches
  build/unapply-patches
  ci/submodule-sync.sh
  patches/revert_nvcomp4.patch
  pom.xml
  thirdparty/cudf-pins/versions.json
Labels: build, feature request

#2492 Quick fix errors in the submodule sync script [skip ci]
  ci/submodule-sync.sh
Labels: bug

#2471 Avoid parsing field name twice when matching named instruction in `get_json_object` kernel
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/json_parser.cuh
Labels: performance

#2497 Nvcomp revert followup
  ci/submodule-sync.sh
  patches/revert_nvcomp4.patch
  pom.xml
  thirdparty/cudf-pins/versions.json
Labels: build

#2504 Make submodule-sync always try update cudf-pins [skip ci]
  ci/submodule-sync.sh
Labels: bug, build
