Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-06, with the labels that each got.

#3405 Apply change to HostTableJni to remove confusion in cuDF builds
  src/main/cpp/src/HostTableJni.cpp
Labels: bug

#3397 Use a common object library to avoid repeated compilation when building C++ tests
  src/main/cpp/tests/CMakeLists.txt
Labels: build

#3484 Update 25.08 cuda12 default to 12.9.1
  build/build-in-docker
  build/run-in-docker
  ci/Dockerfile
  ci/Jenkinsfile.premerge
Labels: build

#3479 Expose the row index of one failed row when casting floats to decimals.
  src/main/cpp/src/DecimalUtilsJni.cpp
  src/main/cpp/src/decimal_utils.cu
  src/main/cpp/src/decimal_utils.hpp
  src/main/java/com/nvidia/spark/rapids/jni/DecimalUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/DecimalUtilsTest.java
Labels: bug, enhancement
