Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-05, with the labels that each got.

#3138 Replace `GPU_ARCHS` build variable by `CMAKE_CUDA_ARCHITECTURES`
  CONTRIBUTING.md
  build/buildcpp.sh
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build, tech debt

#3198 Drop cuda11 and make cuda12 as default
  CONTRIBUTING.md
  build/build-in-docker
  build/run-in-docker
  ci/Dockerfile
  ci/Jenkinsfile.premerge
  ci/nightly-build.sh
  pom.xml
  src/main/cpp/faultinj/README.md
Labels: build

#3186 Leverage cudf's compilation flags and definitions
  pom.xml
  src/main/cpp/CMakeLists.txt
  src/main/cpp/benchmarks/CMakeLists.txt
  src/main/cpp/cmake/Modules/ConfigureCUDA.cmake
  src/main/cpp/tests/CMakeLists.txt
Labels: enhancement, build, tech debt

#3190 Kudo short validity fix
  src/main/cpp/src/shuffle_assemble.cu
  src/main/cpp/tests/shuffle_split.cu
Labels: bug, performance

#3205 Fix compile warnings and errors
  src/main/cpp/benchmarks/common/generate_input.cu
  src/main/cpp/src/cast_decimal_to_string.cu
  src/main/cpp/src/datetime_truncate.cu
  src/main/cpp/src/decimal_utils.cu
  src/main/cpp/src/from_json_to_structs.cu
  src/main/cpp/src/histogram.cu
  src/main/cpp/src/json_utils.cu
  src/main/cpp/src/number_converter.cu
  src/main/cpp/src/row_conversion.cu
  src/main/cpp/tests/hyper_log_log_plus_plus.cu
Labels: bug, build, tech debt

#3234 Add deepwiki badge [skip ci]
  README.md
Labels: documentation

#3242 Fix compile warnings when comparing unsigned char to zero
  src/main/cpp/src/cast_string.cu
  src/main/cpp/src/cast_string_to_float.cu
Labels: bug, tech debt

#3250 Fix compiler warning on `arm64` platform
  src/main/cpp/src/cast_string.cu
  src/main/cpp/src/cast_string_to_float.cu
Labels: bug

#3221 Reuse `libcudf` dependencies when they are available
  build/buildcpp.sh
  src/main/cpp/CMakeLists.txt
Labels: enhancement, build

#3293 TempFix: Skip failing test in `KudoGpuSerializerTest`
  src/test/java/com/nvidia/spark/rapids/jni/kudo/KudoGpuSerializerTest.java
Labels: test

#3175 Upgrade `ccache` in Dockerfile
  ci/Dockerfile
Labels: enhancement, build

#2628 Add design doc for memory tracking in the plugin
  docs/img/memory_state_machine.png
  docs/memory_management.md
  src/main/cpp/src/SparkResourceAdaptorJni.cpp
Labels: documentation

#3379 Support running build container in non-UTC timezone
  build/run-in-docker
Labels: build
