Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-04, with the labels that each got.

#3074 Improve docker image to enable `gcc-toolset` by default
  ci/Dockerfile
Labels: enhancement, build

#3126 Fixed a discrepancy between CPU and GPU kud0 validity data.
  src/main/cpp/src/shuffle_split.cu
  src/main/cpp/tests/shuffle_split.cu
Labels: bug

#3145 Replace calls to cudf's deprecated functions
  src/main/cpp/src/get_json_object.cu
  src/main/cpp/src/histogram.cu
  src/main/cpp/src/hyper_log_log_plus_plus.cu
  src/main/cpp/src/row_conversion.cu
  src/main/cpp/src/shuffle_assemble.cu
Labels: build

#3072 Add Timezone Rule
  src/main/java/com/nvidia/spark/rapids/jni/GpuTimeZoneDB.java
  src/test/java/com/nvidia/spark/rapids/jni/TimeZoneTest.java
Labels: feature request

#3169 Fix `GpuTimeZoneDB#isSupportedTimeZone`
  src/main/java/com/nvidia/spark/rapids/jni/GpuTimeZoneDB.java
Labels: bug

#3171 Cleanup `gcc-toolset` in docker build
  build/run-in-docker
  ci/Jenkinsfile.premerge
  ci/submodule-sync.sh
Labels: enhancement, build

#3133 Fix bugs in CMake build
  src/main/cpp/CMakeLists.txt
  src/main/cpp/cmake/get_flatbuffers.cmake
  thirdparty/cudf-pins/add_dependency_pins.cmake
Labels: build, tech debt

#3180 Override CTK with HOST_CUDA_PATH
  build/run-in-docker
Labels: enhancement
