Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-02, with the labels that each got.

#2892 Disable shared memmory aggregations in CUDF
  patches/disable_shared_agg.patch
  patches/noop.patch
Labels: bug

#2931 Fix spdlog compilation to unblock submodule sync
  src/main/cpp/cmake/get_spdlog.cmake
Labels: bug, build

#2920 Apply groupby patch based on rapidsai/cudf#17985 to branch-24.12
  patches/fix_groupby.patch
Labels: bug

#2936 Update version to 24.12.2-SNAPSHOT
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build

#2940 Revert "Apply groupby patch based on rapidsai/cudf#17985..." from branch-24.12 hotfix [skip ci]
  patches/fix_groupby.patch
Labels: build

#2945 Fix kudo bug when concating validity buffer.
  src/main/java/com/nvidia/spark/rapids/jni/kudo/KudoTableMerger.java
  src/test/java/com/nvidia/spark/rapids/jni/kudo/KudoConcatValidityTest.java
Labels: bug

#2954 Update CMake version to 3.30.4
  ci/Dockerfile
  src/main/cpp/CMakeLists.txt
Labels: build

#2969 Configure only for phase 1 to accelarate the submodule-sync process
  build/buildcpp.sh
  ci/submodule-sync.sh
  pom.xml
Labels: build

#2921 Add support for `org.apache.spark.sql.catalyst.expressions.Slice`
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/ListSliceJni.cpp
  src/main/cpp/src/list_slice.cu
  src/main/cpp/src/list_slice.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/list_slice.cpp
  src/main/java/com/nvidia/spark/rapids/jni/GpuListSliceUtils.java
  src/test/java/com/nvidia/spark/rapids/jni/GpuListSliceUtilsTest.java
Labels: feature request
