Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-09, with the labels that each got.

#3426 [DOC] explain more to convince explicitly using pool thread [skip ci]
  docs/memory_management.md
Labels: documentation

#3730 Update pre-merge CI to use cuda 13.0.1
  ci/Jenkinsfile.premerge
Labels: build

#3704 Enable shellcheck workflow and fix existed issues [skip ci]
  .github/workflows/shell-check.yml
  build/apply-patches
  build/run-in-docker
  build/unapply-patches
  ci/deploy.sh
Labels: build

#3770 Copy cudf floating point rounding code into spark-rapids-jni
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/ArithmeticJni.cpp
  src/main/cpp/src/round_float.cu
  src/main/cpp/src/round_float.hpp
  src/main/java/com/nvidia/spark/rapids/jni/Arithmetic.java
  src/main/java/com/nvidia/spark/rapids/jni/RoundMode.java
  src/test/java/com/nvidia/spark/rapids/jni/ArithmeticTest.java
Labels: feature request

#3782 Update round comment [skip ci]
  src/main/cpp/src/round_float.hpp
Labels: documentation
