Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-01, with the labels that each got.

#2739 Add CODEOWNERS file with team [skip ci]
  .github/CODEOWNERS
Labels: build

#2733 Improve struct pruning logic for Parquet Schema Filtering
  src/main/cpp/src/NativeParquetJni.cpp
Labels: bug

#2742 Add in a hot fix for a CUDF parquet issue
  patches/0_hot_fix_parquet.patch
  patches/noop.patch
Labels: bug

#2748 Revert "Add in a hot fix for a CUDF parquet issue (#2742)"
  patches/0_hot_fix_parquet.patch
  patches/noop.patch
Labels: build

#2749 Update version to 24.12.1
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build

#2751 Merge branch-24.12 into main [skip ci]
  patches/0_hot_fix_parquet.patch
  patches/noop.patch
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: bug

#2752 Fix auto merge conflict 2750 [skip ci]
  pom.xml
  src/main/cpp/CMakeLists.txt
Labels: build

#2756 Update to use vulnerability-scan runner [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2758 Remove inactive user from github workflow [skip ci]
  .github/workflows/blossom-ci.yml
Labels: build

#2782 Use common add-to-project action [skip ci]
  .github/workflows/add-to-project.yml
Labels: build

#2799 Port of cudf::contiguous_split into spark_rapids_jni
  src/main/cpp/src/shuffle_split.cu
Labels: enhancement
