Repository NVIDIA/spark-rapids-jni, pull requests merged in 2025-07, with the labels that each got.

#3504 Add an utility for ANSI
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/ArithmeticJni.cpp
  src/main/cpp/src/error.hpp
  src/main/cpp/src/multiply.cu
  src/main/cpp/src/multiply.hpp
  src/main/cpp/src/row_error_utilities.cu
  src/main/cpp/src/row_error_utilities.hpp
  src/main/cpp/tests/CMakeLists.txt
  src/main/cpp/tests/exception_with_row_index.cpp
  src/main/java/com/nvidia/spark/rapids/jni/Arithmetic.java
  src/main/java/com/nvidia/spark/rapids/jni/ExceptionWithRowIndex.java
  src/test/java/com/nvidia/spark/rapids/jni/ArithmeticTest.java
Labels: performance

#3566 Fix bug in multiply
  src/main/cpp/CMakeLists.txt
  src/main/cpp/src/ArithmeticJni.cpp
  src/main/cpp/src/exception_with_row_index.hpp
  src/main/cpp/src/exception_with_row_index_utilities.cu
  src/main/cpp/src/exception_with_row_index_utilities.hpp
  src/main/cpp/src/multiply.cu
  src/main/cpp/tests/exception_with_row_index.cpp
  src/main/cpp/tests/multiply.cpp
Labels: bug

#3582 Manually update `versions.json` to fix breaking changes in `rapids-cmake`
  thirdparty/cudf-pins/versions.json
Labels: build

#3583 Remove unnecessary calls to `cudf::jni::auto_set_device` in `SparkResourceAdaptorJni.cpp`
  src/main/cpp/src/SparkResourceAdaptorJni.cpp
Labels: tech debt
